---
title: "Simulation Setup"
author: "Tinke Klomp"
date: "24-5-2022"
output: pdf_document
---
original script by Hanne Oberman
use ctrl+shift+c to un-comment tests



```{r setup, include=FALSE}
# packages
library(dplyr)
library(mvtnorm)
library(mice)
library(miceadds)
library(tidyverse)
library(reticulate)
```


```{r}
#importing python package IterativeImputer
sk_ex <- import("sklearn.experimental")
sk_ex$enable_iterative_imputer
sk <- import("sklearn.impute")
#create object for IterativeImputer function
it_im <- sk$IterativeImputer
```


```{r}
# functions
miceadds::source.all("./functions")

# randomness
set.seed(1)

# parameters
n_sim <- 2
n_obs <- 200
betas <- c(-0.5, -0.1, 0.1, 0.5)
mis_mech = c("MCAR", "MAR")
mis_prop = c(0.1, 0.25, 0.5)
```

Test Lower Level Functions
```{r}
# #generate data
# dat <- generate_data(n_obs, betas)
# 
# # ampute data
# amps <- ampute_data(dat, mis_mech = "MAR", mis_prop = 0.5)
# 
# # apply complete case analysis
# CCA <- apply_CCA(amps[[1]])
# 
# # impute data with MICE
# MICE <- apply_MICE(amps[[1]])

# impute data with python
# def apply_PYTHON(amp):
#   imp = it_im("transform(amp)")
#   
#   return(ests)
  
apply_PYTHON <- function(amp){
  # imputation with Python
  imp <- it_im("transform(amp)")
  # fit regression on each imputation
  est <- with(imp, lm(Y ~ X1 + X2 + X3 + X4)) %>%
    # pool results
    mice::pool() %>%
    # clean results
    broom::tidy(conf.int = TRUE) %>%
    # select estimates
    select(term, estimate, conf.low, conf.high) %>%
    # add method name
    cbind(method = "MICE", mech = amp$mech, prop = amp$prop, .)
  # output
  return(est)
}

 PYTHON <- apply_PYTHON(amps[[1]])
```

Test Higher Level Functions
```{r}
# amps <- create_data()
# ests <- apply_methods(amps)
```

Combine into one function
```{r}
simulate_once <- function(n_obs, betas, mis_mech, mis_prop) {
  # generate incomplete data
  amps <- create_data(
    sample_size = n_obs,
    effects = betas,
    mechanisms = mis_mech,
    proportions = mis_prop
  )
  # estimate regression coefficients
  ests <- apply_methods(amps)
  # output
  return(ests)
}
```

Test Simulation Function
```{r}
#ests <- simulate_once(n_obs, betas, mis_mech, mis_prop)
```
```{r}
results_raw <- replicate(
  n_sim, 
  simulate_once(n_obs, betas, mis_mech, mis_prop),
  simplify = FALSE
)
# save raw results
saveRDS(results_raw, "./Results/raw.RDS")
```



RESULTATEN
bias
coverage rate
CI width





